version: '3'

services:
    nginx:
        build: './nginx'
        ports:
            - "80:80"
            - "8080:8080"
            - "8081:8081"
            - "8082:8082"
            - "8083:8083"
            - "8084:8084"
            - "8090:8090"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/logs:/etc/nginx/logs
            - ${WWW_PATH}:/usr/local/lx-www
        depends_on:
            - php
        networks:
            localhost:
                aliases:
                    - nginx-net
        restart: always

    redis-6379:
        build: './redis/6379'
        ports:
            - '6379:6379'
        volumes:
            - ./redis/6379:/usr/local/redis
        networks:
            localhost:
                aliases:
                    - redis-6379-net
        sysctls:
            net.core.somaxconn: 65535
        restart: always

    # redis-6378:
    #     build: './redis/6378'
    #     ports:
    #         - '6378:6378'
    #     volumes:
    #         - ./redis/6378:/usr/local/redis
    #     networks:
    #         localhost:
    #             aliases:
    #                 - redis-6378-net

    redis-6380:
        build: './redis/6380'
        ports:
            - '6380:6380'
        volumes:
            - ./redis/6380:/usr/local/redis
        networks:
            localhost:
                aliases:
                    - redis-6380-net
        sysctls:
            net.core.somaxconn: 65535
        restart: always

    php:
        build: ./php
        ports:
            - "9000:9000"
        volumes:
            - ./php/php.ini:/usr/local/etc/php/php.ini
            - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf
            - ./php/php-fpm.d:/usr/local/etc/php-fpm.d
            - ${WWW_PATH}:/usr/local/lx-www
        networks:
            localhost:
                aliases:
                    - php-net
        restart: always

    # mysql:
    #     build: ./mysql
    #     environment:
    #         MYSQL_ROOT_PASSWORD: "Ashabi123.."
    #         MYSQL_USER: "ms_db"
    #         MYSQL_PASS: "Ashabi123"
    #     ports:
    #         - '3306:3306'
    #     volumes:
    #         - ./mysql/my.cnf:/usr/local/mysql/my.cnf
    #         - ./mysql/data:/usr/local/mysql/data
    #     networks:
    #         localhost:
    #             aliases:
    #                 - mysql-net
    #     restart: always

networks:
    localhost:
        driver: bridge
