version: '3'

services:
    nginx:
        build: './nginx'
        container_name: docker-nginx
        ports:
            - "80:80"
            - "8080:8080"
            - "8081:8081"
            - "8082:8082"
            - "8083:8083"
            - "8084:8084"
            - "8090:8090"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/logs:/etc/nginx/logs
            - ${WWW_PATH}:/usr/local/lx-www
        depends_on:
            - php-fpm
        networks:
            localhost:
                aliases:
                    - nginx
        restart: always

    # redis-6378:
    #     build: './redis/6378'
    #     ports:
    #         - '6378:6378'
    #     volumes:
    #         - ./redis/6378:/usr/local/redis
    #     networks:
    #         localhost:
    #             aliases:
    #                 - redis-6378

    redis-6379:
        build: './redis/6379'
        container_name: docker-redis-6379
        ports:
            - '6379:6379'
        volumes:
            - ./redis/6379:/usr/local/redis
            - ${WWW_PATH}/lx-script/redis:/usr/local/script
        networks:
            localhost:
                aliases:
                    - redis-6379
        sysctls:
            net.core.somaxconn: 65535
        restart: always

    redis-6380:
        build: './redis/6380'
        container_name: docker-redis-6380
        ports:
            - '6380:6380'
        volumes:
            - ./redis/6380:/usr/local/redis
            - ${WWW_PATH}/lx-script/redis:/usr/local/script
        networks:
            localhost:
                aliases:
                    - redis-6380
        sysctls:
            net.core.somaxconn: 65535
        restart: always

    php-fpm:
        build: ./php-fpm
        container_name: docker-php-fpm
        ports:
            - "9000:9000"
        volumes:
            - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
            - ./php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
            - ./php-fpm/php-fpm.d:/usr/local/etc/php-fpm.d
            - ${WWW_PATH}:/usr/local/lx-www
        networks:
            localhost:
                aliases:
                    - php-fpm
        depends_on:
            - mysql-3306
        restart: always

    php-swoole:
        build: ./php-swoole
        container_name: docker-php-swoole
        ports:
            - "9555:9555"
        volumes:
            - ./php-swoole/php.ini:/usr/local/etc/php/php.ini
            - ./php-swoole/php-fpm.conf:/usr/local/etc/php-fpm.conf
            - ./php-swoole/php-fpm.d:/usr/local/etc/php-fpm.d
            - ${WWW_PATH}/thinkphp:/usr/local/thinkphp
        command: 
            - /bin/sh
            - -c
            - |
                cd /usr/local/thinkphp
                php think swoole:server
        networks:
            localhost:
                aliases:
                    - php-swoole
        depends_on:
            - mysql-3306
        restart: always

    mysql-3306:
        build: ./mysql/3306
        container_name: docker-mysql-3306
        environment:
            MYSQL_ROOT_PASSWORD: "Ashabi123.."
            TZ: "Asia/Shanghai"
            # MYSQL_DATABASE: "ms_db_main"
            # MYSQL_USER: "ms_db"
            # MYSQL_PASSWORD: "Ashabi123"
        ports:
            - '3306:3306'
        volumes:
            - ./mysql/3306/my.cnf:/etc/mysql/my.cnf
            - ./mysql/3306/data:/var/lib/mysql
            - ./mysql/3306/db:/var/lib/db
            - ./mysql/3306/init:/docker-entrypoint-initdb.d
        command: --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp=true
        networks:
            localhost:
                aliases:
                    - mysql-3306
        restart: always

    mysql-3307:
        build: ./mysql/3307
        container_name: docker-mysql-3307
        environment:
            MYSQL_ROOT_PASSWORD: "Ashabi123.."
            TZ: "Asia/Shanghai"
            # MYSQL_DATABASE: "ms_db_main"
            # MYSQL_USER: "ms_db"
            # MYSQL_PASSWORD: "Ashabi123"
        ports:
            - '3307:3307'
        volumes:
            - ./mysql/3307/my.cnf:/etc/mysql/my.cnf
            - ./mysql/3307/data:/var/lib/mysql
            - ./mysql/3307/db:/var/lib/db
            - ./mysql/3307/init:/docker-entrypoint-initdb.d
        command: --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp=true
        networks:
            localhost:
                aliases:
                    - mysql-3307
        restart: always
# --remove-orphans flag
    # composer:
    #     build: ./composer
    #     container_name: docker-composer

networks:
    localhost:
        driver: bridge


