FROM mysql:5.7

# RUN set -ex \
#     && sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
#     && apk update \
#     && apk add --no-cache --update tzdata \
#     && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
#     && apk del tzdata
